# Generated by Django 5.0.7 on 2025-04-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('contractor', 'A-List Home Pro'), ('crew', 'Crew'), ('specialist', 'Specialist'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
