# Generated by Django 5.0.7 on 2025-04-09 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alistpros_profiles', '0001_initial'),
        ('contractors', '0002_initial'),
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='alistpro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='alistpros_profiles.alisthomeproprofile'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_received_old', to='contractors.contractorprofile'),
        ),
        migrations.CreateModel(
            name='AListHomeProStripeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_account_id', models.CharField(max_length=255)),
                ('is_details_submitted', models.BooleanField(default=False)),
                ('is_charges_enabled', models.BooleanField(default=False)),
                ('is_payouts_enabled', models.BooleanField(default=False)),
                ('onboarding_url', models.TextField(blank=True, null=True)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('onboarding_started_at', models.DateTimeField(auto_now_add=True)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('last_webhook_type', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alistpro_stripe_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='StripeAccount',
        ),
        migrations.CreateModel(
            name='StripeAccount',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.alisthomeprostripeaccount',),
        ),
    ]
